steps:
  # Step 1: Build Application Image
  - name: 'docker'
    id: 'build-app'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cinch-fakhri-repo/app:${SHORT_SHA}'
      - '.'

  # Step 2: Push Image to Artifact Registry
  - name: 'docker'
    id: 'push-app'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cinch-fakhri-repo/app:${SHORT_SHA}'
    waitFor: ['build-app']

  # Step 3: Deploy to Cloud Run with secrets and Cloud SQL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args:
      - 'run'
      - 'deploy'
      - 'cinch-fakhri-service'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/cinch-fakhri-repo/app:${SHORT_SHA}'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:asia-southeast1:test-cinch'
      - '--set-secrets'
      - 'POSTGRES_USER=DB_USER:latest'
      - '--set-secrets'
      - 'POSTGRES_PASSWORD=DB_PASSWORD:latest'
      - '--set-secrets'
      - 'DATABASE_URL=database_url:latest'
      - '--set-env-vars'
      - |
        API_PORT=8000,
        API_V1_STR=/api/v1,
        DEBUG=True,
        PROJECT_NAME=Cinch API,
        POSTGRES_DB=test-cinch,
        POSTGRES_HOST=/cloudsql/${PROJECT_ID}:asia-southeast1:test-cinch,
        POSTGRES_PORT=5432
    waitFor: ['push-app']

options:
  logging: CLOUD_LOGGING_ONLY 