version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-cinch
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - API_PORT=8000
      - DEBUG=true
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/test-cinch
    command: >
      sh -c "
        while ! pg_isready -h db -p 5432 -U postgres; do
          echo 'Waiting for database to be ready'
          sleep 1
        done &&
        echo 'Database is ready' &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - cinch-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-cinch
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/app
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./scripts/populate_tables.sql:/app/scripts/populate_tables.sql
      - ./scripts/seed_test_data.sql:/app/scripts/seed_test_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cinch-network

volumes:
  postgres_data:

networks:
  cinch-network:
    driver: bridge 